name: 'bigdata_at3'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  bigdata_at3:
    silver:
      +schema: bronze_silver
      +materialized: table
    gold:
      +schema: bronze_gold
      +materialized: table
    datamart:            
      +schema: bronze_datamarts
      +materialized: view

